const brandsData = [
    {
        id: 0,
        "year":"15 Years",
        "NMSID": 7707,
        "src": "https://i.postimg.cc/bJK5G0m2/six.webp",
        "aprRate": "3.6% APR",
        "date": "Mar 10",
        "rate": "3.500% Rate",
        "point": "1 Point",
        "lockRate": "30 Rate Lock",
        "fees": "$898.09",
        "feespoint": "1 Point",
        "feesLock": "20 Rate Lock",
        "toll": "(887) 407 - 37123",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 1,
        "year":"30 Years",
        "NMSID": 1234,
        "src": "https://i.postimg.cc/t458rx4L/five.webp",
        "aprRate": "8.2% APR",
        "date": "Jan 15",
        "rate": "8.000% Rate",
        "point": "0.75 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$110.00",
        "feespoint": "1.75 Points",
        "feesLock": "50 Rate Lock",
        "toll": "(000) 555 - 1234",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 2,
        "year":"30 Years",
        "NMSID": 7707,
        "src": "https://i.postimg.cc/fTYG9FnW/eight.webp",
        "aprRate": "3.6% APR",
        "date": "Mar 10",
        "rate": "3.500% Rate",
        "point": "1 Point",
        "lockRate": "30 Rate Lock",
        "fees": "$898.09",
        "feespoint": "1 Point",
        "feesLock": "20 Rate Lock",
        "toll": "(887) 407 - 37123",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 3,
        "year":"15 Years",
        "NMSID": 1234,
        "src": "https://i.postimg.cc/MGpNgpcX/four.webp",
        "aprRate": "8.2% APR",
        "date": "July 15",
        "rate": "4.000% Rate",
        "point": "6.75 Points",
        "lockRate": "75 Rate Lock",
        "fees": "$300.00",
        "feespoint": "8.75 Points",
        "feesLock": "80 Rate Lock",
        "toll": "(99) 75 - 1234",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 4,
        "year":"20 Years",
        "NMSID": 2468,
        "src": "https://i.postimg.cc/5tKTJWvg/one.webp",
        "aprRate": "9.9% APR",
        "date": "Feb 20",
        "rate": "0.750% Rate",
        "point": "8.25 Points",
        "lockRate": "60 Rate Lock",
        "fees": "$50.50",
        "feespoint": "4.25 Points",
        "feesLock": "4 Rate Lock",
        "toll": "(7) 13 - 567",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 5,
        "year":"20 Years",
        "NMSID": 7707,
        "src": "https://i.postimg.cc/Jnyg4Y5L/seven.webp",
        "aprRate": "3.6% APR",
        "date": "Mar 10",
        "rate": "3.500% Rate",
        "point": "1 Point",
        "lockRate": "30 Rate Lock",
        "fees": "$898.09",
        "feespoint": "1 Point",
        "feesLock": "20 Rate Lock",
        "toll": "(887) 407 - 37123",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 6,
        "year":"15 Years",
        "NMSID": 1234,
        "src": "https://i.postimg.cc/bJK5G0m2/six.webp",
        "aprRate": "4.2% APR",
        "date": "Sep 15",
        "rate": "6.000% Rate",
        "point": "2.75 Points",
        "lockRate": "15 Rate Lock",
        "fees": "$5.00",
        "feespoint": "7.75 Points",
        "feesLock": "70 Rate Lock",
        "toll": "(100) 555 - 1234",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 7,
        "year":"20 Years",
        "NMSID": 2468,
        "src": "https://i.postimg.cc/vTfN51K2/three.webp",
        "aprRate": "3.9% APR",
        "date": "May 20",
        "rate": "3.750% Rate",
        "point": "1.25 Points",
        "lockRate": "60 Rate Lock",
        "fees": "$1050.50",
        "feespoint": "1.25 Points",
        "feesLock": "45 Rate Lock",
        "toll": "(877) 123 - 4567",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 8,
        "year":"20 Years",
        "NMSID": 9876,
        "src": "https://i.postimg.cc/CMqt3tKC/two.jpg",
        "aprRate": "4.5% APR",
        "date": "Jun 5",
        "rate": "4.250% Rate",
        "point": "1.5 Points",
        "lockRate": "30 Rate Lock",
        "fees": "$090.75",
        "feespoint": "1.5 Points",
        "feesLock": "30 Rate Lock",
        "toll": "(888) 987 - 6543",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 9,
        "year":"20 Years",
        "NMSID": 1357,
        "src": "https://i.postimg.cc/N0Yy8Zzg/bitmap.png",
        "aprRate": "3.8% APR",
        "date": "Jul 12",
        "rate": "3.650% Rate",
        "point": "1.1 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$825.30",
        "feespoint": "1.1 Points",
        "feesLock": "20 Rate Lock",
        "toll": "(866) 543 - 2109",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 10,
        "year":"20 Years",
        "NMSID": 7707,
        "src": "https://i.postimg.cc/5tKTJWvg/one.webp",
        "aprRate": "3.6% APR",
        "date": "Mar 10",
        "rate": "3.500% Rate",
        "point": "1 Point",
        "lockRate": "30 Rate Lock",
        "fees": "$898.09",
        "feespoint": "1 Point",
        "feesLock": "20 Rate Lock",
        "toll": "(887) 407 - 37123",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 11,
        "year":"20 Years",
        "NMSID": 12345,
        "src": "https://i.postimg.cc/t458rx4L/five.webp",
        "aprRate": "5.2% APR",
        "date": "Jun 15",
        "rate": "3.000% Rate",
        "point": "1.75 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$250.00",
        "feespoint": "1.75 Points",
        "feesLock": "20 Rate Lock",
        "toll": "(100) 225 - 1234",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 12,
        "year":"15 Years",
        "NMSID": 6789,
        "src": "https://i.postimg.cc/N0Yy8Zzg/bitmap.png",
        "aprRate": "3.9% APR",
        "date": "Oct 20",
        "rate": "9.750% Rate",
        "point": "85 Points",
        "lockRate": "60 Rate Lock",
        "fees": "$670.50",
        "feespoint": "1.25 Points",
        "feesLock": "45 Rate Lock",
        "toll": "(8) 93 - 4567",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 13,
        "year":"30 Years",
        "NMSID": 24680,
        "src": "https://i.postimg.cc/bJK5G0m2/six.webp",
        "aprRate": "4.5% APR",
        "date": "Jun 5",
        "rate": "4.250% Rate",
        "point": "1.5 Points",
        "lockRate": "30 Rate Lock",
        "fees": "$950.75",
        "feespoint": "1.5 Points",
        "feesLock": "30 Rate Lock",
        "toll": "(888) 987 - 6543",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 14,
        "year":"30 Years",
        "NMSID": 13579,
        "src": "https://i.postimg.cc/vTfN51K2/three.webp",
        "aprRate": "5.8% APR",
        "date": "Jul 12",
        "rate": "3.650% Rate",
        "point": "1.1 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$3425.30",
        "feespoint": "4.1 Points",
        "feesLock": "50 Rate Lock",
        "toll": "(800) 513 - 2509",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 15,
        "year":"30 Years",
        "NMSID": 7707,
        "src": "https://i.postimg.cc/CMqt3tKC/two.jpg",
        "aprRate": "3.6% APR",
        "date": "Mar 10",
        "rate": "3.500% Rate",
        "point": "1 Point",
        "lockRate": "30 Rate Lock",
        "fees": "$898.09",
        "feespoint": "1 Point",
        "feesLock": "20 Rate Lock",
        "toll": "(887) 407 - 37123",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 16,
        "year":"20 Years",
        "NMSID": 12345,
        "src": "https://i.postimg.cc/P5dhShTF/bitmap.jpg",
        "aprRate": "4.2% APR",
        "date": "Apr 15",
        "rate": "4.000% Rate",
        "point": "0.75 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$750.00",
        "feespoint": "0.75 Points",
        "feesLock": "30 Rate Lock",
        "toll": "(800) 555 - 1234",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 17,
        "year":"20 Years",
        "NMSID": 6789,
        "src": "https://i.postimg.cc/bJK5G0m2/six.webp",
        "aprRate": "9.9% APR",
        "date": "Aug 20",
        "rate": "6.750% Rate",
        "point": "5.25 Points",
        "lockRate": "6 Rate Lock",
        "fees": "$50.50",
        "feespoint": "1.25 Points",
        "feesLock": "45 Rate Lock",
        "toll": "(877) 123 - 4567",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 18,
        "year":"15 Years",
        "NMSID": 24680,
        "src": "https://i.postimg.cc/5tKTJWvg/one.webp",
        "aprRate": "4.5% APR",
        "date": "July 50",
        "rate": "6.250% Rate",
        "point": "2.5 Points",
        "lockRate": "30 Rate Lock",
        "fees": "$190.75",
        "feespoint": "5.5 Points",
        "feesLock": "10 Rate Lock",
        "toll": "(008) 987 - 6543",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 19,
        "year":"30 Years",
        "NMSID": 1379,
        "src": "https://i.postimg.cc/CMqt3tKC/two.jpg",
        "aprRate": "6.1% APR",
        "date": "Mar 11",
        "rate": "6.950% Rate",
        "point": "1.1 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$005.30",
        "feespoint": "3.9 Points",
        "feesLock": "500 Rate Lock",
        "toll": "(10) 543 - 2109",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 20,
        "year":"20 Years",
        "NMSID": 9876,
        "src": "https://i.postimg.cc/N0Yy8Zzg/bitmap.png",
        "aprRate": "4.0% APR",
        "date": "Aug 20",
        "rate": "3.750% Rate",
        "point": "1.2 Points",
        "lockRate": "60 Rate Lock",
        "fees": "$900.00",
        "feespoint": "1.2 Points",
        "feesLock": "45 Rate Lock",
        "toll": "(855) 234 - 5678",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 21,
        "year":"20 Years",
        "NMSID": 5432,
        "src": "https://i.postimg.cc/L50fNvZx/bitmap.png",
        "aprRate": "3.5% APR",
        "date": "Sep 8",
        "rate": "3.250% Rate",
        "point": "0.5 Points",
        "lockRate": "30 Rate Lock",
        "fees": "$600.25",
        "feespoint": "0.5 Points",
        "feesLock": "20 Rate Lock",
        "toll": "(877) 987 - 4321",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 22,
        "year":"15 Years",
        "NMSID": 24601,
        "src": "https://i.postimg.cc/vTfN51K2/three.webp",
        "aprRate": "4.1% APR",
        "date": "Oct 14",
        "rate": "3.800% Rate",
        "point": "1.3 Points",
        "lockRate": "60 Rate Lock",
        "fees": "$950.00",
        "feespoint": "1.3 Points",
        "feesLock": "30 Rate Lock",
        "toll": "(800) 123 - 4567",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 23,
        "year":"15 Years",
        "NMSID": 319,
        "src": "https://i.postimg.cc/P5dhShTF/bitmap.jpg",
        "aprRate": "3.9% APR",
        "date": "Nov 22",
        "rate": "3.600% Rate",
        "point": "1.1 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$825.00",
        "feespoint": "1.1 Points",
        "feesLock": "20 Rate Lock",
        "toll": "(866) 543 - 2109",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 24,
        "year":"15 Years",
        "NMSID": 98765,
        "src": "https://i.postimg.cc/fTYG9FnW/eight.webp",
        "aprRate": "3.7% APR",
        "date": "Dec 15",
        "rate": "3.450% Rate",
        "point": "0.8 Points",
        "lockRate": "30 Rate Lock",
        "fees": "$720.00",
        "feespoint": "0.8 Points",
        "feesLock": "30 Rate Lock",
        "toll": "(888) 765 - 4321",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 25,
        "year":"15 Years",
        "NMSID": 7707,
        "src": "https://i.postimg.cc/vTfN51K2/three.webp",
        "aprRate": "3.6% APR",
        "date": "Mar 10",
        "rate": "3.500% Rate",
        "point": "1 Point",
        "lockRate": "30 Rate Lock",
        "fees": "$898.09",
        "feespoint": "1 Point",
        "feesLock": "20 Rate Lock",
        "toll": "(887) 407 - 37123",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 26,
        "year":"15 Years",
        "NMSID": 12345,
        "src": "https://i.postimg.cc/t458rx4L/five.webp",
        "aprRate": "4.2% APR",
        "date": "Apr 15",
        "rate": "4.000% Rate",
        "point": "1.75 Points",
        "lockRate": "11 Rate Lock",
        "fees": "$110.00",
        "feespoint": "3.75 Points",
        "feesLock": "40 Rate Lock",
        "toll": "(90) 85 - 1234",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 27,
        "year":"30 Years",
        "NMSID": 6789,
        "src": "https://i.postimg.cc/P5dhShTF/bitmap.jpg",
        "aprRate": "1.9% APR",
        "date": "Apr 20",
        "rate": "1.750% Rate",
        "point": "15 Points",
        "lockRate": "1 Rate Lock",
        "fees": "$50.50",
        "feespoint": "1.25 Points",
        "feesLock": "45 Rate Lock",
        "toll": "(7) 13 - 4567",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 28,
        "year":"30 Years",
        "NMSID": 9876,
        "src": "https://i.postimg.cc/fTYG9FnW/eight.webp",
        "aprRate": "4.0% APR",
        "date": "Aug 20",
        "rate": "3.750% Rate",
        "point": "1.2 Points",
        "lockRate": "60 Rate Lock",
        "fees": "$900.00",
        "feespoint": "1.2 Points",
        "feesLock": "45 Rate Lock",
        "toll": "(855) 234 - 5678",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 29,
        "NMSID": 5432,
        "year":"15 Years",
        "src": "https://i.postimg.cc/N0Yy8Zzg/bitmap.png",
        "aprRate": "5.5% APR",
        "date": "Mar 8",
        "rate": "7.250% Rate",
        "point": "4.5 Points",
        "lockRate": "60 Rate Lock",
        "fees": "$300.25",
        "feespoint": "2.5 Points",
        "feesLock": "70 Rate Lock",
        "toll": "(8) 97 - 4321",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 30,
        "year":"30 Years",
        "NMSID": 24601,
        "src": "https://i.postimg.cc/P5dhShTF/bitmap.jpg",
        "aprRate": "4.1% APR",
        "date": "Oct 14",
        "rate": "3.800% Rate",
        "point": "1.3 Points",
        "lockRate": "6 Rate Lock",
        "fees": "$950.00",
        "feespoint": "1.3 Points",
        "feesLock": "30 Rate Lock",
        "toll": "(80) 123 - 4567",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 31,
        "year":"20 Years",
        "NMSID": 909,
        "src": "https://i.postimg.cc/Jnyg4Y5L/seven.webp",
        "aprRate": "3.9% APR",
        "date": "Nov 22",
        "rate": "3.600% Rate",
        "point": "1.1 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$825.00",
        "feespoint": "1.1 Points",
        "feesLock": "20 Rate Lock",
        "toll": "(866) 543 - 2109",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 32,
        "year":"20 Years",
        "NMSID": 98765,
        "src": "https://i.postimg.cc/CMqt3tKC/two.jpg",
        "aprRate": "3.7% APR",
        "date": "Dec 15",
        "rate": "3.450% Rate",
        "point": "0.8 Points",
        "lockRate": "30 Rate Lock",
        "fees": "$720.00",
        "feespoint": "0.8 Points",
        "feesLock": "30 Rate Lock",
        "toll": "(888) 765 - 4321",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 33,
        "year":"20 Years",
        "NMSID": 2468,
        "src": "https://i.postimg.cc/P5dhShTF/bitmap.jpg",
        "aprRate": "4.2% APR",
        "date": "Aug 5",
        "rate": "3.800% Rate",
        "point": "1.2 Points",
        "lockRate": "60 Rate Lock",
        "fees": "$120.00",
        "feespoint": "4.2 Points",
        "feesLock": "90 Rate Lock",
        "toll": "(00) 123 - 4567",
        "tolldesc": "Call for inquiries"
    },

    {
        id: 34,
        "year":"20 Years",
        "NMSID": 7890,
        "src": "https://i.postimg.cc/N0Yy8Zzg/bitmap.png",
        "aprRate": "3.5% APR",
        "date": "Sep 18",
        "rate": "3.450% Rate",
        "point": "0.9 Points",
        "lockRate": "30 Rate Lock",
        "fees": "$650.50",
        "feespoint": "0.9 Points",
        "feesLock": "15 Rate Lock",
        "toll": "(888) 555 - 7890",
        "tolldesc": "Free consultation available"
    }
    ,
    {
        id: 35,
        "year":"20 Years",
        "NMSID": 1234,
        "src": "https://i.postimg.cc/L50fNvZx/bitmap.png",
        "aprRate": "4.0% APR",
        "date": "Jul 28",
        "rate": "3.750% Rate",
        "point": "1.0 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$800.75",
        "feespoint": "1.0 Points",
        "feesLock": "25 Rate Lock",
        "toll": "(877) 987 - 6543",
        "tolldesc": "Speak to our experts"
    }
    ,
    {
        id: 36,
        "year":"30 Years",
        "NMSID": 179,
        "src": "https://i.postimg.cc/P5dhShTF/bitmap.jpg",
        "aprRate": "3.8% APR",
        "date": "Jul 12",
        "rate": "3.650% Rate",
        "point": "1.1 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$825.30",
        "feespoint": "1.1 Points",
        "feesLock": "20 Rate Lock",
        "toll": "(866) 543 - 2109",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 37,
        "year":"30 Years",
        "NMSID": 5678,
        "src": "https://i.postimg.cc/Jnyg4Y5L/seven.webp",
        "aprRate": "3.6% APR",
        "date": "Aug 15",
        "rate": "3.550% Rate",
        "point": "0.8 Points",
        "lockRate": "60 Rate Lock",
        "fees": "$700.20",
        "feespoint": "0.8 Points",
        "feesLock": "30 Rate Lock",
        "toll": "(866) 222 - 3333",
        "tolldesc": "Call us anytime"
    },
    {
        id: 38,
        "year":"30 Years",
        "NMSID": 24680,
        "src": "https://i.postimg.cc/L50fNvZx/bitmap.png",
        "aprRate": "4.5% APR",
        "date": "Jun 5",
        "rate": "4.250% Rate",
        "point": "1.5 Points",
        "lockRate": "30 Rate Lock",
        "fees": "$1220.75",
        "feespoint": "1.5 Points",
        "feesLock": "30 Rate Lock",
        "toll": "(888) 987 - 6543",
        "tolldesc": "Toll-free, no obligations"
    },
    {
        id: 39,
        "year":"20 Years",
        "NMSID": 9876,
        "src": "https://i.postimg.cc/CMqt3tKC/two.jpg",
        "aprRate": "3.9% APR",
        "date": "Sep 5",
        "rate": "3.700% Rate",
        "point": "1.0 Points",
        "lockRate": "45 Rate Lock",
        "fees": "$850.00",
        "feespoint": "1.0 Points",
        "feesLock": "20 Rate Lock",
        "toll": "(844) 123 - 9876",
        "tolldesc": "Contact us for details"
    }
]
export default brandsData;